### ISSUE TITLE
Package import error

### ISSUE THREAD

**Issue by waltari** [evekb/evedev-kb#109]
Never had any issues with this killboard but recently this thing popd up all of sudden when i tried to install it on a subdomain instead of maindomain/kb. Needless to say there were NO serverside changes whatsoever.

Trying to connect to the provided MySQL server now...
Connected to MySQL server running Version '10.1.41-MariaDB'.
Successfully selected database 'kb_1000066', everything seems fine. Please continue.

Checking database engine InnoDB... 
InnoDB is supported on your MySQL Server
Reading packages...Inserting data (15/130) into kb3_invtypesusing file ../packages/database/kb3_invtypes/sql_tbldata_invtypes.sql_p10.sql.gz...File ../packages/database/kb3_invtypes/sql_tbldata_invtypes.sql_p10.sql.gz had 10 lines with 10 queries.

2 queries failed.error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''The scrambler rifle is a selective-fire weapon capable of semi-automatic and ch' at line 1error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'left unmanaged, thermal stresses age the focusing crystal prematurely, resulting' at line 1Automatic reload in 20s for next chunk because an error occurred.
--

**Comment by Salvoxia** [comment]
Hi,

that might be caused by an oversight after the last database update.
Could you please check if the change referenced above fixes your problem?

Best Regards,
Salvoxia

**Comment by waltari** [comment]
Hi, yes that fixed the installation issue however when i try to load killmails from either of my characters i get this

WARNING [2] gzopen(cache/store/c4/32/c43265f627a532838d9a8df632a81a83): failed to open stream: No such file or directory
Warning: filesize(): stat failed for cache/error.log in /srv/_container/_1000066/web/content/www/killboard/common/includes/class.edkerror.php on line 83
WARNING [2] filesize(): stat failed for cache/error.log
Error on line 83 in file /srv/_container/_1000066/web/content/www/killboard/common/includes/class.edkerror.php
PHP 7.1.30 (Linux), EDK 4.4.3.0 (July 2019 1.0)
File: /srv/_container/_1000066/web/content/www/killboard/common/includes/class.edkerror.php, line: 83, function: filesize
File: /srv/_container/_1000066/web/content/www/killboard/common/includes/class.edkerror.php, line: 99, class: EDKError, function: checkAndRollLogFile

**Comment by Salvoxia** [comment]
Hi,

this now looks like the cache directory is not writable for PHP. Can you please verify this?

Best Regards,
Salvoxia

**Comment by waltari** [comment]
Hello, the permissions for entire killboard are set to Read, Write, Execute, so that shouldnt be the problem. The weird thing about this is a fact that this error pops up only when i try to fetch data from zKill via pilot API or by login in via SSO. When i post killmail manually all seems fine and syndication from another community evedev-kb works without problems as well. I will check the required scopes once again but i already did it twice. I will also try to move it on another host that runs on PHP 5.6 instead of 7

**Comment by Salvoxia** [comment]
Hi,

the error you posted occurred during log file writing. So if the killboard doesn't have anything to write to the log file, it doesn't seem to be a problem. 
However, it doesn't seem to have a problem writing the esi cache to cache/esi, but seems it cannot access cache/error.log. Can you check the permissions on that file specifically (as it was not part of the installation package but should have been created later)?

The SSO scopes should not come into play when fetching from zKB and PHP 7 should not be a problem either.

Best Regards,
Salvoxia

**Comment by waltari** [comment]
Well, the cache problems are gone, the problem seems to be https, as soon as i have set the certificate up, those cache errors are gone but the gzopen is still there.

WARNING [2] gzopen(/srv/_container/_1000066/web/content/www/killboard/common/includes/class.pageassembly.php): failed to open stream: No such file or directory
Error on line : 72, class: pSsoRegistration function: handleFinishSsoRegistration
PHP 7.1.30 (Linux), EDK 4.4.3.0 (July 2019 1.0)
WARNING [2] gzopen(cache/store/c4/32/c43265f627a532838d9a8df632a81a83): failed to open stream: No such file or directory
Error on line 31 in file /srv/_container/_1000066/web/content/www/killboard/common/ssoregistration.php
PHP 7.1.30 (Linux), EDK 4.4.3.0 (July 2019 1.0)

edit: checked once again and all files and folders are set to read/write/execute 777, all except install folder

edit2: moved to different host with php 5.6 and reinstalled. Every error i did get so far is gone, but iam getting new one when trying to set up SSO. Again everything is Read/Write/Execute

Fatal error: Uncaught Error: Call to a member function getCharacterID() on null in /srv/_container/_1000066/web/content/www/killboard/common/admin/admin_esisso.php:170 Stack trace: #0 /srv/_container/_1000066/web/content/www/killboard/common/index.php(324): include() #1 /srv/_container/_1000066/web/content/www/killboard/index.php(26): include('/srv/_container...') #2 {main} thrown in /srv/_container/_1000066/web/content/www/killboard/common/admin/admin_esisso.php on line 170

**Comment by Salvoxia** [comment]
> Fatal error: Uncaught Error: Call to a member function getCharacterID() on null in /srv/_container/_1000066/web/content/www/killboard/common/admin/admin_esisso.php:170 Stack trace: #0 /srv/_container/_1000066/web/content/www/killboard/common/index.php(324): include() #1 /srv/_container/_1000066/web/content/www/killboard/index.php(26): include('/srv/_container...') #2 {main} thrown in /srv/_container/_1000066/web/content/www/killboard/common/admin/admin_esisso.php on line 170

That could happen if you don't actually have any SSO keys for any characters in your database (maybe the registration did not complete successfully?) or none the keys you have are marked as "enabled" on the ESI SSO page and you try to fetch kills.

![image](https://user-images.githubusercontent.com/6501566/62857731-a3f27d00-bcf8-11e9-8dd4-91ad3f00c204.png)
